<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit120e9bf9c4b604c8818277885bd6c43a
{
    public static $files = array (
        '7b11c4dc42b3b3023073cb14e519683c' => __DIR__ . '/..' . '/ralouphie/getallheaders/src/getallheaders.php',
        '6e3fae29631ef280660b3cdad06f25a8' => __DIR__ . '/..' . '/symfony/deprecation-contracts/function.php',
        '37a3dc5111fe8f707ab4c132ef1dbc62' => __DIR__ . '/..' . '/guzzlehttp/guzzle/src/functions_include.php',
    );

    public static $prefixLengthsPsr4 = array (
        't' => 
        array (
            'thiagoalessio\\TesseractOCR\\' => 27,
        ),
        's' => 
        array (
            'setasign\\Fpdi\\' => 14,
        ),
        'c' => 
        array (
            'chillerlan\\Settings\\' => 20,
            'chillerlan\\QRCode\\' => 18,
        ),
        'Z' => 
        array (
            'ZipStream\\' => 10,
        ),
        'S' => 
        array (
            'Spatie\\PdfToImage\\' => 18,
        ),
        'P' => 
        array (
            'Psr\\SimpleCache\\' => 16,
            'Psr\\Http\\Message\\' => 17,
            'Psr\\Http\\Client\\' => 16,
            'PhpOffice\\PhpSpreadsheet\\' => 25,
            'PHPMailer\\PHPMailer\\' => 20,
        ),
        'M' => 
        array (
            'Matrix\\' => 7,
        ),
        'I' => 
        array (
            'Intervention\\Image\\' => 19,
            'Intervention\\Gif\\' => 17,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Psr7\\' => 16,
            'GuzzleHttp\\Promise\\' => 19,
            'GuzzleHttp\\' => 11,
        ),
        'E' => 
        array (
            'Endroid\\QrCode\\' => 15,
        ),
        'D' => 
        array (
            'DASPRiD\\Enum\\' => 13,
        ),
        'C' => 
        array (
            'Composer\\Pcre\\' => 14,
            'Complex\\' => 8,
            'Com\\Tecnick\\Unicode\\Data\\' => 25,
            'Com\\Tecnick\\Unicode\\' => 20,
            'Com\\Tecnick\\Pdf\\Page\\' => 21,
            'Com\\Tecnick\\Pdf\\Image\\' => 22,
            'Com\\Tecnick\\Pdf\\Graph\\' => 22,
            'Com\\Tecnick\\Pdf\\Font\\' => 21,
            'Com\\Tecnick\\Pdf\\Encrypt\\' => 24,
            'Com\\Tecnick\\Pdf\\' => 16,
            'Com\\Tecnick\\File\\' => 17,
            'Com\\Tecnick\\Color\\' => 18,
            'Com\\Tecnick\\Barcode\\' => 20,
            'ClickSend\\' => 10,
        ),
        'B' => 
        array (
            'BaconQrCode\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'thiagoalessio\\TesseractOCR\\' => 
        array (
            0 => __DIR__ . '/..' . '/thiagoalessio/tesseract_ocr/src',
        ),
        'setasign\\Fpdi\\' => 
        array (
            0 => __DIR__ . '/..' . '/setasign/fpdi/src',
        ),
        'chillerlan\\Settings\\' => 
        array (
            0 => __DIR__ . '/..' . '/chillerlan/php-settings-container/src',
        ),
        'chillerlan\\QRCode\\' => 
        array (
            0 => __DIR__ . '/..' . '/chillerlan/php-qrcode/src',
        ),
        'ZipStream\\' => 
        array (
            0 => __DIR__ . '/..' . '/maennchen/zipstream-php/src',
        ),
        'Spatie\\PdfToImage\\' => 
        array (
            0 => __DIR__ . '/..' . '/spatie/pdf-to-image/src',
        ),
        'Psr\\SimpleCache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/simple-cache/src',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-factory/src',
            1 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Psr\\Http\\Client\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-client/src',
        ),
        'PhpOffice\\PhpSpreadsheet\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpoffice/phpspreadsheet/src/PhpSpreadsheet',
        ),
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
        'Matrix\\' => 
        array (
            0 => __DIR__ . '/..' . '/markbaker/matrix/classes/src',
        ),
        'Intervention\\Image\\' => 
        array (
            0 => __DIR__ . '/..' . '/intervention/image/src',
        ),
        'Intervention\\Gif\\' => 
        array (
            0 => __DIR__ . '/..' . '/intervention/gif/src',
        ),
        'GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'GuzzleHttp\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/promises/src',
        ),
        'GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
        'Endroid\\QrCode\\' => 
        array (
            0 => __DIR__ . '/..' . '/endroid/qr-code/src',
        ),
        'DASPRiD\\Enum\\' => 
        array (
            0 => __DIR__ . '/..' . '/dasprid/enum/src',
        ),
        'Composer\\Pcre\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/pcre/src',
        ),
        'Complex\\' => 
        array (
            0 => __DIR__ . '/..' . '/markbaker/complex/classes/src',
        ),
        'Com\\Tecnick\\Unicode\\Data\\' => 
        array (
            0 => __DIR__ . '/..' . '/tecnickcom/tc-lib-unicode-data/src',
        ),
        'Com\\Tecnick\\Unicode\\' => 
        array (
            0 => __DIR__ . '/..' . '/tecnickcom/tc-lib-unicode/src',
        ),
        'Com\\Tecnick\\Pdf\\Page\\' => 
        array (
            0 => __DIR__ . '/..' . '/tecnickcom/tc-lib-pdf-page/src',
        ),
        'Com\\Tecnick\\Pdf\\Image\\' => 
        array (
            0 => __DIR__ . '/..' . '/tecnickcom/tc-lib-pdf-image/src',
        ),
        'Com\\Tecnick\\Pdf\\Graph\\' => 
        array (
            0 => __DIR__ . '/..' . '/tecnickcom/tc-lib-pdf-graph/src',
        ),
        'Com\\Tecnick\\Pdf\\Font\\' => 
        array (
            0 => __DIR__ . '/..' . '/tecnickcom/tc-lib-pdf-font/src',
        ),
        'Com\\Tecnick\\Pdf\\Encrypt\\' => 
        array (
            0 => __DIR__ . '/..' . '/tecnickcom/tc-lib-pdf-encrypt/src',
        ),
        'Com\\Tecnick\\Pdf\\' => 
        array (
            0 => __DIR__ . '/..' . '/tecnickcom/tc-lib-pdf/src',
        ),
        'Com\\Tecnick\\File\\' => 
        array (
            0 => __DIR__ . '/..' . '/tecnickcom/tc-lib-file/src',
        ),
        'Com\\Tecnick\\Color\\' => 
        array (
            0 => __DIR__ . '/..' . '/tecnickcom/tc-lib-color/src',
        ),
        'Com\\Tecnick\\Barcode\\' => 
        array (
            0 => __DIR__ . '/..' . '/tecnickcom/tc-lib-barcode/src',
        ),
        'ClickSend\\' => 
        array (
            0 => __DIR__ . '/..' . '/clicksend/clicksend-php/lib',
        ),
        'BaconQrCode\\' => 
        array (
            0 => __DIR__ . '/..' . '/bacon/bacon-qr-code/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'FPDF' => __DIR__ . '/..' . '/setasign/fpdf/fpdf.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit120e9bf9c4b604c8818277885bd6c43a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit120e9bf9c4b604c8818277885bd6c43a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit120e9bf9c4b604c8818277885bd6c43a::$classMap;

        }, null, ClassLoader::class);
    }
}
