<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => null,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => null,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bacon/bacon-qr-code' => array(
            'pretty_version' => 'v3.0.1',
            'version' => '3.0.1.0',
            'reference' => 'f9cc1f52b5a463062251d666761178dbdb6b544f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bacon/bacon-qr-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'chillerlan/php-qrcode' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'reference' => '42e215640e9ebdd857570c9e4e52245d1ee51de2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chillerlan/php-qrcode',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'chillerlan/php-settings-container' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '95ed3e9676a1d47cab2e3174d19b43f5dbf52681',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chillerlan/php-settings-container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'clicksend/clicksend-php' => array(
            'pretty_version' => 'v5.0.79',
            'version' => '5.0.79.0',
            'reference' => '1a5ee58a36cd260cdbce8f270680f02de2593c0d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../clicksend/clicksend-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/pcre' => array(
            'pretty_version' => '3.3.2',
            'version' => '3.3.2.0',
            'reference' => 'b2bed4734f0cc156ee1fe9c0da2550420d99a21e',
            'type' => 'library',
            'install_path' => __DIR__ . '/./pcre',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dasprid/enum' => array(
            'pretty_version' => '1.0.6',
            'version' => '1.0.6.0',
            'reference' => '8dfd07c6d2cf31c8da90c53b83c026c7696dda90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dasprid/enum',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'endroid/qr-code' => array(
            'pretty_version' => '6.0.3',
            'version' => '6.0.3.0',
            'reference' => 'bdbb06e767efe9abe3c00461662b4059a6cd0b55',
            'type' => 'library',
            'install_path' => __DIR__ . '/../endroid/qr-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.9.2',
            'version' => '7.9.2.0',
            'reference' => 'd281ed313b989f213357e3be1a179f02196ac99b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => 'f9c436286ab2892c7db7be8c8da4ef61ccf7b455',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.7.0',
            'version' => '2.7.0.0',
            'reference' => 'a70f5c95fb43bc83f07c9c948baa0dc1829bf201',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'intervention/gif' => array(
            'pretty_version' => '4.2.2',
            'version' => '4.2.2.0',
            'reference' => '5999eac6a39aa760fb803bc809e8909ee67b451a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../intervention/gif',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'intervention/image' => array(
            'pretty_version' => '3.11.3',
            'version' => '3.11.3.0',
            'reference' => 'd0f097b8a3fa8fb758efc9440b513aa3833cda17',
            'type' => 'library',
            'install_path' => __DIR__ . '/../intervention/image',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maennchen/zipstream-php' => array(
            'pretty_version' => '3.1.2',
            'version' => '3.1.2.0',
            'reference' => 'aeadcf5c412332eb426c0f9b4485f6accba2a99f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maennchen/zipstream-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/complex' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => '95c56caa1cf5c766ad6d65b6344b807c1e8405b9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/complex',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/matrix' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '728434227fe21be27ff6d86621a1b13107a2562c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/matrix',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.9.3',
            'version' => '6.9.3.0',
            'reference' => '2f5c94fe7493efc213f643c23b1b1c249d40f47e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpoffice/phpspreadsheet' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => '2d4b9f3582102aafb6b1378fff8a20eeeacfb31c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpspreadsheet',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'bb5906edc1c324c9a05aa0873d40117941e5fa90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '2b4765fddfe3b508ac62f829e852b1501d3f6e8a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'reference' => '402d35bcb92c70c026d1a6a9883f06b2ead23d71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '764e0b3939f5ca87cb904f570ef9be2d78a07865',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'setasign/fpdf' => array(
            'pretty_version' => '1.8.6',
            'version' => '1.8.6.0',
            'reference' => '0838e0ee4925716fcbbc50ad9e1799b5edfae0a0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../setasign/fpdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'setasign/fpdi' => array(
            'pretty_version' => 'v2.6.3',
            'version' => '2.6.3.0',
            'reference' => '67c31f5e50c93c20579ca9e23035d8c540b51941',
            'type' => 'library',
            'install_path' => __DIR__ . '/../setasign/fpdi',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spatie/pdf-to-image' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'reference' => '9a5cb264a99e87e010c65d4ece03b51f821d55bd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/pdf-to-image',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v3.5.1',
            'version' => '3.5.1.0',
            'reference' => '74c71c939a79f7d5bf3c1ce9f5ea37ba0114c6f6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-barcode' => array(
            'pretty_version' => '2.4.3',
            'version' => '2.4.3.0',
            'reference' => '8d65345d64cdcf8f5e254bd24f26c7e5f966befa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-barcode',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-color' => array(
            'pretty_version' => '2.2.8',
            'version' => '2.2.8.0',
            'reference' => '77d68d5206aef08ee0f3b69c0c6df4e559ad28bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-color',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-file' => array(
            'pretty_version' => '2.1.3',
            'version' => '2.1.3.0',
            'reference' => 'a14a94795a393e6dec252a24fac307ffa1d0aa3d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-file',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-pdf' => array(
            'pretty_version' => '8.0.85',
            'version' => '8.0.85.0',
            'reference' => 'b0eb7997d96255000bbd6f46a463340828a55e2b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-pdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-pdf-encrypt' => array(
            'pretty_version' => '2.1.11',
            'version' => '2.1.11.0',
            'reference' => '058119347fb15d0473a9b056b8ee504c393ed515',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-pdf-encrypt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-pdf-font' => array(
            'pretty_version' => '2.6.6',
            'version' => '2.6.6.0',
            'reference' => '316bdc5bdf820a564be05d7efcb194254f8982c3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-pdf-font',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-pdf-graph' => array(
            'pretty_version' => '2.2.7',
            'version' => '2.2.7.0',
            'reference' => '26e61ae5d77c1a17579e7a515eb59bd01b5c4ddf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-pdf-graph',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-pdf-image' => array(
            'pretty_version' => '2.1.7',
            'version' => '2.1.7.0',
            'reference' => '5c203b9cab4204c3ad2cb839f07789f45ebe9355',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-pdf-image',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-pdf-page' => array(
            'pretty_version' => '4.2.6',
            'version' => '4.2.6.0',
            'reference' => '5b0b4efe1e03e0cb6d4638f4d69cf83bf2152097',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-pdf-page',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-unicode' => array(
            'pretty_version' => '2.0.19',
            'version' => '2.0.19.0',
            'reference' => '568fcc0dad08c11d6f2f6a6bfc6e4795fe4739a8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-unicode',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-unicode-data' => array(
            'pretty_version' => '2.0.19',
            'version' => '2.0.19.0',
            'reference' => 'e07852d634f30e3c06280633339f7c6c636348e8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-unicode-data',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'thiagoalessio/tesseract_ocr' => array(
            'pretty_version' => '2.13.0',
            'version' => '2.13.0.0',
            'reference' => '232a8cb9d571992f9bd1e263f2f6909cf6c173a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../thiagoalessio/tesseract_ocr',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
